version: '3.8'

services:
  neo4j:
    image: neo4j:5.14.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  qdrant:
    image: qdrant/qdrant:v1.7.0
    ports:
      - "6333:6333"  # HTTP
      - "6334:6334"  # GRPC
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  neo4j_data:
  neo4j_logs:
  qdrant_data: 